package exceptions

import scala.util.control.Exception

abstract class ValidacionException extends Exception 

case class TransporteTieneVolumenInsuficienteParaRealizarElEnvio() extends ValidacionException
case class TransporteNoSoportaElTipoEnvioEspecificado() extends ValidacionException
case class TransporteNoSeDirigeALaSucursalDeDestinoEspecificada() extends ValidacionException
case class LaSucursalDeDestinoNoTieneSuficienteEspacioDisponible() extends ValidacionException
case class TransporteNoPoseeInfraestructura() extends ValidacionException